name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.17.2
    - name: Create build directory
      run: mkdir build/
    - name: Run CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TEST=true -DBUILD_ENGINE=true
    - name: Build
      run: cmake --build .
    - name: Test
      working-directory: ./engine
      run: ctest
