name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: Create build directory
      run: mkdir build
    - name: Generate CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build CMake
      run: cmake --build build
    - name: Test
      run: ctest --test-dir build
